

WITH datos_d AS (
    SELECT 
        DOCUMENTACION,
        ANIO
    FROM HSU.int_bst_expedientes
    GROUP BY DOCUMENTACION, ANIO
    HAVING COUNT(*) > 1
),

datos_netos AS (
    SELECT
        TIPO_DOCUMENTACION,
        DOCUMENTACION,
        DNI_ANONIMO,
        NOMBRE,
        APELLIDO1,
        APELLIDO2,
        INICIALS_NOM_I_2_LLINATGES,
        MAIL,
        TELEFONO,
        CONSIDERACION,
        DIRECCION,
        PROVINCIA,
        MUNICIPIO,
        CODIGO_POSTAL,
        CUENTA_BANCARIA,
        COMERCIALIZADORA,
        ANIO,
        ZONA_CLIMATICA,
        IMPORTE as IMPORT
    FROM HSU.int_bst_expedientes
)

SELECT 
    TIPO_DOCUMENTACION,
    DOCUMENTACION,
    DNI_ANONIMO,
    NOMBRE,
    APELLIDO1,
    APELLIDO2,
    INICIALS_NOM_I_2_LLINATGES,
    MAIL,
    TELEFONO,
    CONSIDERACION,
    DIRECCION,
    PROVINCIA,
    MUNICIPIO,
    CODIGO_POSTAL,
    CUENTA_BANCARIA,
    COMERCIALIZADORA,
    ANIO,
    ZONA_CLIMATICA,
    IMPORT,
    NULL as DUPLICADO,
    'N' as IS_DUPLICADO
FROM datos_netos
WHERE DOCUMENTACION NOT IN (SELECT DOCUMENTACION FROM datos_d WHERE ANIO = datos_netos.ANIO)

UNION ALL

SELECT
    t1.TIPO_DOCUMENTACION,
    t1.DOCUMENTACION,
    t1.DNI_ANONIMO,
    t1.NOMBRE,
    t1.APELLIDO1,
    t1.APELLIDO2,
    t1.INICIALS_NOM_I_2_LLINATGES,
    t1.MAIL,
    t1.TELEFONO,
    t1.CONSIDERACION,
    t1.DIRECCION,
    t1.PROVINCIA,
    t1.MUNICIPIO,
    t1.CODIGO_POSTAL,
    t1.CUENTA_BANCARIA,
    t1.COMERCIALIZADORA,
    t1.ANIO,
    t1.ZONA_CLIMATICA,
    t1.IMPORT,
    LISTAGG(t2.COMERCIALIZADORA, ' ') WITHIN GROUP (ORDER BY t2.COMERCIALIZADORA) AS DUPLICADO,
    'S' as IS_DUPLICADO
FROM datos_netos t1
LEFT JOIN datos_netos t2 ON t2.DOCUMENTACION = t1.DOCUMENTACION AND t2.ANIO = t1.ANIO
WHERE t1.DOCUMENTACION IN (SELECT DOCUMENTACION FROM datos_d)
AND t1.ANIO IN (SELECT ANIO FROM datos_d WHERE DOCUMENTACION = t1.DOCUMENTACION)
GROUP BY
    t1.TIPO_DOCUMENTACION,
    t1.DOCUMENTACION,
    t1.DNI_ANONIMO,
    t1.NOMBRE,
    t1.APELLIDO1,
    t1.APELLIDO2,
    t1.INICIALS_NOM_I_2_LLINATGES,
    t1.MAIL,
    t1.TELEFONO,
    t1.CONSIDERACION,
    t1.DIRECCION,
    t1.PROVINCIA,
    t1.MUNICIPIO,
    t1.CODIGO_POSTAL,
    t1.CUENTA_BANCARIA,
    t1.COMERCIALIZADORA,
    t1.ANIO,
    t1.ZONA_CLIMATICA,
    t1.IMPORT